const staticFilePath = "/static/"

export default {
  "samples/6581__ST_012.wav": {
    name: "buzz1",
    category: "Sound Effect",
    path: `${staticFilePath}samples/6581__ST_012.wav`,
    gain: 0.8,
    gainCorrection: 1.0,
    mute: false,
    solo: false,
  },
  "samples/8580_PST_060.wav": {
    name: "beep1",
    category: "Sound Effect",
    path: `${staticFilePath}samples/8580_PST_060.wav`,
    gain: 0.8,
    gainCorrection: 1.0,
    mute: false,
    solo: false,
  },
  "samples/8580_PST_090.wav": {
    name: "beep2",
    category: "Sound Effect",
    path: `${staticFilePath}samples/8580_PST_090.wav`,
    gain: 0.8,
    gainCorrection: 1.0,
    mute: false,
    solo: false,
  },
  "samples/8580_P_T_078.wav": {
    name: "8580_P_T_078",
    category: "Sound Effect",
    path: `${staticFilePath}samples/8580_P_T_078.wav`,
    gain: 0.8,
    gainCorrection: 1.0,
    mute: false,
    solo: false,
  },
  "samples/clave.wav": {
    name: "clave",
    category: "Misc. Percussion",
    path: `${staticFilePath}samples/clave.wav`,
    gain: 0.8,
    gainCorrection: 1.0,
    mute: false,
    solo: false,
  },
  "samples/cowbell.wav": {
    name: "cowbell",
    category: "Misc. Percussion",
    path: `${staticFilePath}samples/cowbell.wav`,
    gain: 0.8,
    gainCorrection: 1.0,
    mute: false,
    solo: false,
  },
  "samples/hi_hat.wav": {
    name: "hihat1",
    category: "Cymbol",
    path: `${staticFilePath}samples/hi_hat.wav`,
    gain: 0.8,
    gainCorrection: 1.0,
    mute: false,
    solo: false,
  },
  "samples/hihat.wav": {
    name: "hihat2",
    category: "Cymbol",
    path: `${staticFilePath}samples/hihat.wav`,
    gain: 0.8,
    gainCorrection: 1.0,
    mute: false,
    solo: false,
  },
  "samples/kick.wav": {
    name: "kick",
    category: "Bass Drum",
    path: `${staticFilePath}samples/kick.wav`,
    gain: 0.8,
    gainCorrection: 1.0,
    mute: false,
    solo: false,
  },
  "samples/snare.wav": {
    name: "snare",
    category: "Snare",
    path: `${staticFilePath}samples/snare.wav`,
    gain: 0.8,
    gainCorrection: 0.7,
    mute: false,
    solo: false,
  },
  "samples/Kicks/Cymatics - Trap Kick 1 - C.wav": {
    name: "Trap Kick 1 - C",
    category: "Bass Drum",
    path: `${staticFilePath}samples/Kicks/Cymatics - Trap Kick 1 - C.wav`,
    gain: 0.8,
    gainCorrection: 0.8,
    mute: false,
    solo: false,
  },
  "samples/Kicks/Cymatics - Dubstep Kick 3 - E.wav": {
    name: "Dubstep Kick 3 - E",
    category: "Bass Drum",
    path: `${staticFilePath}samples/Kicks/Cymatics - Dubstep Kick 3 - E.wav`,
    gain: 0.8,
    gainCorrection: 0.5,
    mute: false,
    solo: false,
  },
  "samples/Snare/Cymatics - Titan Snare 3 - C.wav": {
    name: "Titan Snare 3 - C",
    category: "Snare",
    path: `${staticFilePath}samples/Snares/Cymatics - Titan Snare 3 - C.wav`,
    gain: 0.5,
    gainCorrection: 0.3,
    mute: false,
    solo: false,
  },
  "samples/Snare/Cymatics - Dubstep Snare 6 - G.wav": {
    name: "Dubstep Snare 6 - G",
    category: "Snare",
    path: `${staticFilePath}samples/Snares/Cymatics - Dubstep Snare 6 - G.wav`,
    gain: 0.8,
    gainCorrection: 0.4,
    mute: false,
    solo: false,
  },
  "samples/Percussion/Cymatics - Grime Perc 25.wav": {
    name: "Grime Perc 25",
    category: "Misc. Percussion",
    path: `${staticFilePath}samples/Percussion/Cymatics - Grime Perc 25.wav`,
    gain: 0.8,
    gainCorrection: 0.8,
    mute: false,
    solo: false,
  },
  "samples/Percussion/Cymatics - Synth Perc 28.wav": {
    name: "Synth Perc 28",
    category: "Misc. Percussion",
    path: `${staticFilePath}samples/Percussion/Cymatics - Synth Perc 28.wav`,
    gain: 0.8,
    gainCorrection: 0.8,
    mute: false,
    solo: false,
  },
}
